<a href="https://colab.research.google.com/github/Rushikesh042/Python-for-Data-Science/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [3]:
import numpy as np
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3, 4, 5])

In [6]:
my_mat = [[1,2,3],[4,5,6],[3,4,5]]
arra = np.array(my_mat)

In [7]:
arra

array([[1, 2, 3],
       [4, 5, 6],
       [3, 4, 5]])

In [12]:
import numpy as np
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [14]:
 np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
arr = np.linspace(0,5,10)
arr


array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [23]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.random.rand(5)

array([0.12123785, 0.1296326 , 0.96648545, 0.13419826, 0.11931753])

In [25]:
np.random.rand(5,5)

array([[0.4541459 , 0.96609759, 0.98021973, 0.04784538, 0.99723002],
       [0.57558111, 0.76887238, 0.97498118, 0.77552232, 0.19131581],
       [0.31056511, 0.95801755, 0.56463918, 0.58874879, 0.78726375],
       [0.06508786, 0.1764578 , 0.34076835, 0.33988173, 0.22941242],
       [0.53551404, 0.19754358, 0.4895726 , 0.24834211, 0.18030763]])

In [26]:
np.random.randn(5)

array([ 0.20554577,  1.96581337, -0.89170452, -0.39914328, -0.32946831])

In [27]:
np.random.randn(5,5)

array([[ 1.03843549, -2.45767943, -0.37145032,  1.02794058,  0.89615266],
       [ 0.29395481,  0.39641093,  1.6305608 ,  1.25339349,  0.30097026],
       [-1.58766044,  0.38640709,  1.18400319, -1.06256675,  0.11967087],
       [-1.4174255 ,  0.42962459, -0.55387247, -0.57687257, -0.00293683],
       [ 0.19812809,  0.89461698,  0.86169343,  1.06578116,  0.34601372]])

In [28]:
arr = np.random.randint(1,100,10)

array([ 9,  5, 45, 98, 77,  8, 71, 49, 70, 90])

In [42]:
arr.reshape(2,5)

array([[0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222],
       [2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ]])

In [35]:
arr.max()

5.0

In [43]:
arr.min()

0.0

In [44]:
arr.argmax()

9

In [45]:
arr.argmin()

0

In [47]:
arr.shape

(10,)

In [49]:
arr.dtype

dtype('float64')

In [51]:
arr = arr + 100
arr

array([200.        , 200.55555556, 201.11111111, 201.66666667,
       202.22222222, 202.77777778, 203.33333333, 203.88888889,
       204.44444444, 205.        ])